
CREATE TABLE USERS (
	Username	TEXT	PRIMARY KEY,
	Password	TEXT	NOT NULL,
	FullName	TEXT	NOT NULL,
	-- Location	TEXT	NOT NULL,
	Tokens		INTEGER DEFAULT (0)
	-- "Role"		TEXT(8) NOT NULL
);



CREATE TABLE VENDING_MACHINES (
	VMID		TEXT(8)	PRIMARY KEY,
	VMLocation	Text	NOT NULL
);



CREATE TABLE PRODUCTS (
	ProductID		TEXT(8)	PRIMARY KEY,
	ProductName		TEXT	NOT NULL,
	ProductPrice	INTEGER	NOT NULL
);


CREATE TABLE PRODUCTS_AVAILABLE (
	VMID		TEXT(8)	REFERENCES VENDING_MACHINES(VMID),
	ProductName	TEXT	REFERENCES PRODUCTS(ProductName),
	ProductID	TEXT	REFERENCES	PRODUCTS(ProductID),
	Quantity	INTEGER	NOT NULL
);



CREATE TABLE ADMINS (
	Username	TEXT	PRIMARY KEY,
	Password	TEXT	NOT NULL,
	FullName	TEXT	NOT NULL,
	Role		Text(8)	NOT NULL
);



CREATE TABLE PURCHASES (
	PurchaseID		TEXT(8)	PRIMARY KEY,
	ProductName		TEXT	REFERENCES	PRODUCTS(ProductName),
	ProductID		TEXT	REFERENCES	PRODUCTS(ProductID),
	PurchaseTime	Text	DEFAULT(datetime())
);